# Hledger configuration

# General options
--pretty

# Command-specific options

[balancesheet]
--market
--tree
--drop 1

[cashflow]
--market
--tree
--drop 1

[incomestatement]
--market
--tree
--drop 1
