# Hledger configuration

# General options
--pretty

# Command-specific options

[accounts]
--tree

[balancesheet]
--market
--tree
--no-elide

[cashflow]
--market
--tree
--no-elide

[incomestatement]
--market
--tree
--no-elide
