" Vim configuration

function! s:CheckAndSource(file_path)
  if filereadable(a:file_path)
    execute "source " . a:file_path
  endif
endfunction

" Set Vim config base directory
let s:vimrc_config_dir=fnamemodify(expand($MYVIMRC), ':p:h') . '/config'

" Source configuration files
call s:CheckAndSource(s:vimrc_config_dir . "/global.vim")
call s:CheckAndSource(s:vimrc_config_dir . "/bindings.vim")
call s:CheckAndSource(s:vimrc_config_dir . "/functions.vim")
call s:CheckAndSource(s:vimrc_config_dir . "/filetypes.vim")
call s:CheckAndSource(s:vimrc_config_dir . "/theme.vim")

" Source local configuration file
call s:CheckAndSource(s:vimrc_config_dir . "/local.vim")

unlet s:vimrc_config_dir
delfunction s:CheckAndSource
