# Global settings

# Set tmux-256color as inner terminal
set -g default-terminal tmux-256color

# Enable RGB (24-bit color) for alacritty
set -sa terminal-features ",alacritty*:RGB"

# Enable mouse support
set -g mouse on

# Enable vi keys in copy mode
set -g mode-keys vi
# Enable vi keys in status line
set -g status-keys vi

# Windows start from 1
set -g base-index 1
# Automatic renumbering of windows
set -g renumber-windows on

# Scrolling history
set -g history-limit 20000
