# Theme settings

# Screen title
set -g set-titles on
set -g set-titles-string "#T"

# Status bar
set -g status-left "#{?client_prefix,#[fg=red],#[fg=cyan]}[#S]#[default] "
set -g status-right ""
set -g status-style bg=colour18

# Window status
set -g window-status-current-format "#[fg=yellow]#I#[default]:#W#{?window_flags,#[fg=blue]#{window_flags}, }"
set -g window-status-current-style nodim
set -g window-status-style dim

# Pane border
set -g pane-active-border-style "#{?pane_in_mode,fg=yellow,#{?synchronize-panes,fg=red,fg=cyan}}"
set -g pane-border-style fg=colour18

# Pane numbering
set -g display-panes-colour white
set -g display-panes-active-colour cyan
